version: 0.1
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1)
  build:
    commands:
      - echo $DOCKER_IMAGE_TAG
      - docker build -t audiogram.prx.tech:$DOCKER_IMAGE_TAG .
      - docker tag audiogram.prx.tech:$DOCKER_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/audiogram.prx.tech:$DOCKER_IMAGE_TAG
      # - docker run test
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/audiogram.prx.tech:$DOCKER_IMAGE_TAG
artifacts:
  # It seems like CodePipeline and CodeBuild expect an artifact here. Currently
  # we don't need any, so this is essentially a no-op.
  files:
    - README.md
